service: shortlinker
frameworkVersion: "3"

provider:
    name: aws
    region: us-east-1
    runtime: nodejs18.x
    environment:
        BCRYPT_SALT_ROUNDS: 1
        DYNAMODB_USER_TABLE: ${self:service}-userTable-${sls:stage}
        DYNAMODB_EMAIL_INDEX: ${self:service}-emailIndex-${sls:stage}
        JWT_SECRET: jwt_secret_goes_here
        JWT_EXPIRE_IN: 2h
    iamRoleStatements:
        - Effect: Allow
          Action:
              - lambda:InvokeFunction
          Resource: "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:service}-${sls:stage}-verify-jwt"
        - Effect: Allow
          Action:
              - dynamodb:Query
          Resource:
              - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-userTable-${sls:stage}"
              - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-userTable-${sls:stage}/index/${self:service}-emailIndex-${sls:stage}"
        - Effect: Allow
          Action:
              - dynamodb:PutItem
          Resource:
              - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-userTable-${sls:stage}"

package:
    individually: true

functions:
    signup:
        handler: functions/auth/signup.handler
        name: ${self:service}-${sls:stage}-signup
        package:
            patterns:
                - "node_modules/aws-lambda"
                - "node_modules/@aws-sdk/client-dynamodb"
                - "node_modules/bcryptjs"
                - "node_modules/jsonwebtoken"
        events:
            - httpApi: "POST /auth/signup"
    signin:
        handler: functions/auth/signin.handler
        name: ${self:service}-${sls:stage}-signin
        package:
            patterns:
                - "node_modules/aws-lambda"
                - "node_modules/@aws-sdk/client-dynamodb"
                - "node_modules/bcryptjs"
                - "node_modules/jsonwebtoken"
        events:
            - httpApi: "POST /auth/signin"
    verify-jwt:
        handler: functions/auth/verify-jwt.handler
        name: ${self:service}-${sls:stage}-verify-jwt
        package:
            patterns:
                - "node_modules/jsonwebtoken"
    create-link:
        handler: functions/shortlink/create-link.handler
        name: ${self:service}-${sls:stage}-create-link
        package:
            patterns:
                - "node_modules/aws-lambda"
        events:
            - httpApi: "POST /link"

resources:
    Resources:
        UserTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions:
                    - AttributeName: userId
                      AttributeType: S
                    - AttributeName: email
                      AttributeType: S
                BillingMode: PAY_PER_REQUEST
                KeySchema:
                    - AttributeName: userId
                      KeyType: HASH
                TableName: ${self:service}-userTable-${sls:stage}
                GlobalSecondaryIndexes:
                    - IndexName: ${self:service}-emailIndex-${sls:stage}
                      KeySchema:
                          - AttributeName: email
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL

plugins:
    - serverless-esbuild
    - serverless-offline

custom:
    esbuild:
        bundle: true
        minify: true
