service: shortlinker
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x

functions:
    signup:
        handler: functions/auth/signup.handler
        events:
            - httpApi: "POST /auth/signup"
    signin:
        handler: functions/auth/signin.handler
        events:
            - httpApi: "POST /auth/signin"

plugins:
    - serverless-esbuild
    - serverless-offline

custom:
    esbuild:
        bundle: true
        minify: true
